[project]
name = "energy-trading-system"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "black==25.1.0",
    "cvxpy==1.6.4",
    "isort==6.0.1",
    "mypy==1.15.0",
    "pandas==2.2.3",
    "pandas-stubs==2.2.3.250308",
    "pyarrow==19.0.1",
]
